name: Türkgüven İSG
favicon: null
layout_spectrum: 0.74535
typography_spectrum: 0.39669
title: Türkgüven İSG
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#4b4b4a'
    - '#e52122'
    - '#c9c6c6'
    - '#f08788'
  brandStrength: 0.25
  lightness: 0.75
  saturation: 0.25
  rhythmicContrast: 1
purpose: []
